coverage:
  status:
    project:
      default:
        target: 75%   # overall project coverage must stay >= 75%
        threshold: 2% # allow up to 2% drop without failing
    patch:
      default:
        target: 75%   # changed lines in PR must be >= 75%
        threshold: 0% # no drop allowed for new code

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
