coverage:
  status:
    project:
      default:
        target: 75%   # overall project coverage must be >= 75%
        threshold: 2% # allow small 2% drop without failing
    patch:
      default:
        target: 75%   # changed files in PR must be >= 75%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # true = only comment if coverage changes
